/*
 *
 * User constants
 *
 */

enum ActionTypes {
  USER_LOGIN = 'app/User/USER_LOGIN',
  USER_LOGIN_SUCCESS = 'app/User/USER_LOGIN_SUCCESS',
  USER_LOGIN_FAILED = 'app/User/USER_LOGIN_FAILED',
  USER_RETURN_LOGIN = 'app/User/USER__RETURN_LOGIN_',
  USER_REGISTER = 'app/User/USER_REGISTER',
  USER_REGISTER_SUCCESS = 'app/User/USER_REGISTER_SUCCESS',
  USER_REGISTER_FAILED = 'app/User/USER_REGISTER_FAILED',
  USER_CONFIRM_REGISTER = 'app/User/USER_CONFIRM_REGISTER',
  USER_CONFIRM_REGISTER_SUCCESS = 'app/User/USER_CONFIRM_REGISTER_SUCCESS',
  USER_CONFIRM_REGISTER_FAILED = 'app/User/USER_CONFIRM_REGISTER_FAILED',
}

export default ActionTypes;
