/*
 *
 * Doctors constants
 *
 */

enum ActionTypes {
  CREAT_APPOINTMENT = 'app/Doctors/CREAT_APPOINTMENT',
  CREAT_APPOINTMENT_SUCCESS = 'app/Doctors/CREAT_APPOINTMENT_SUCCESS',
  CREAT_APPOINTMENT_FAILED = 'app/Doctors/CREAT_APPOINTMENT_FAILED',

  CONFIRM_APPOINTMENT = 'app/Doctors/CONFIRM_APPOINTMENT',
  CONFIRM_APPOINTMENT_SUCCESS = 'app/Doctors/CONFIRM_APPOINTMENT_SUCCESS',
  CONFIRM_APPOINTMENT_FAILED = 'app/Doctors/CONFIRM_APPOINTMENT_FAILED',

  SET_NEW_APPOINTMENT_REQUESTED = 'app/Doctors/SET_NEW_APPOINTMENT_REQUESTED',
}

export default ActionTypes;
