/*
 *
 * Doctors constants
 *
 */

enum ActionTypes {
  LIST_DOCTORS = 'app/Doctors/LIST_DOCTORS',
  LIST_DOCTORS_SUCCESS = 'app/Doctors/LIST_DOCTORS_SUCCESS',
  LIST_DOCTORS_FAILED = 'app/Doctors/LIST_DOCTORS_FAILED',

  SEARCH_DOCTORS = 'app/Doctors/SEARCH_DOCTORS',
  SEARCH_DOCTORS_SUCCESS = 'app/Doctors/SEARCH_DOCTORS_SUCCESS',
  SEARCH_DOCTORS_FAILED = 'app/Doctors/SEARCH_DOCTORS_FAILED',

  SELECT_DOCTOR = 'app/Doctors/SELECT_DOCTOR',
  SELECT_DOCTOR_SUCCESS = 'app/Doctors/SELECT_DOCTOR_SUCCESS',
  SELECT_DOCTOR_FAILED = 'app/Doctors/SELECT_DOCTOR_FAILED',
}

export default ActionTypes;
